const events = {
    cse: [
        {
            id: 1,
            title: "Velocity - Type Racer",
            first_price: "1500",
            second_price: "500",
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "10:00 AM - 12:00 PM",
            desc: "Think you're the fastest typist around? Prove it! Join our speed typing event, race against the clock, and claim the title of typing master. Exciting prizes await the winner!",
            rules: [
                "He or she must type the entire passage within the allotted time.",
                "Errors will result in loss of points.",
                "Players with the highest Words Per Minute (WPM) wins the game.",
                "Decision of judge's will be final."
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Manu V V","Harigovind S", "Josekutty George"],
            contact_coordinator: ["8921767709","9188358027","8086671175"],
        },
        {
            id: 2,
            title: "SPEED FREAK - NFS GAMING",
            first_price: "1500",
            second_price: "1000",
            third_price: "500",
            type: "Individual",
            mode: "Offline",
            date: "20",
            time: "9:00 AM - 2:30 PM",
            desc: "Get ready to rev your engines and put your racing skills to the test! Compete in the ultimate LAN multiplayer event of Need for Speed and battle it out against other players for the prestigious Racing King title. Do you have what it takes to be crowned the champion?",
            rules: [
                "Players need ‘Not’ bring their laptop to participate in the event.",
                "Event is conducted as two rounds: Preliminary round and Race round.",
                "The Preliminary Round is a walk-in round. The time of completing the circuit will be recorded. This time is used to shortlist the participants to the next round. Note that this will be an individual event.",
                "In the Race Round, the top 16 shortlisted racers compete with each other to win the Race King title.",
                "The 16 players are split into groups of 4 racers each. Two racers are shortlisted from each group after the race. They are then forwarded to the next round.",
                "There are 3 rounds in total for the Race Round.",
                "Players of each round will be asked if they prefer to have car collision on or off.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Arnold Denzil","Abhiram A", "Shajith Joseph"],
            contact_coordinator: ["8078339113","8089618237","9539147591"],
        },
        {
            id: 3,
            title: "CYBERVERSE – VR GAMING",
            first_price: "1500",
            second_price: NULL,
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "10:00 AM - 4:00 PM",
            desc: "Virtual reality (VR) is a simulated experience that employs pose tracking and 3D near-eye displays to give the user an immersive feel of a virtual world",
            rules: [
                "The event is open to all students who are passionate about VR Gaming.",
                "The event will span for the whole day. ",
                "The grand winner will be decided by the player who sets the highest score.",
                "Participants must follow all instructions given by the organizers.",
                "The decision of the coordinators will be final and binding.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Jubin Thomas","Muhammed Firoz", "Abhijith C A"],
            contact_coordinator: ["9061313287","9496436031","7012904254"],
        },
        {
            id: 4,
            title: "FILM TRIVIA – FILM QUIZ",
            first_price: "1500",
            second_price: "1000",
            third_price: NULL,
            type: "Team(2 Members)",
            mode: "Offline",
            date: "19",
            time: "9:00 AM - 12:00 PM",
            desc: "Lights, camera, laughter!\nGet ready to put your film knowledge to the test with Film Trivia, the ultimate game for movie buffs.",
            rules: [
                "Maximum of 2 participants are allowed in a team.",
                "The team should be present at the time. Those who are late will be not allowed to play the game. ",
                "All teams should be present at least 5 minutes prior to the event.",
                "Malpractices are not allowed, if found will lead to the termination of entire team.",
                "Only English and Malayalam movies will be asked for the game.",
                "Decisions of judges will be final regarding all the matters of the game."
            ],
            reg_fees: "50",
            posterImg: "",
            coordinator: ["Karthik H","Parvathy S", "Anjana", "Vandana Unni"],
            contact_coordinator: ["8547351305","7306862790 ","8129145896","9656095813"],
        },
        {
            id: 5,
            title: "HACKATHON",
            first_price: "4000",
            second_price: NULL,
            third_price: NULL,
            type: "Team(2 Members)",
            mode: "Offline",
            date: "19",
            time: "9:00 AM - 12:00 PM",
            desc: "Ready to unleash your creative beast and slay some problems? Join our Hackathon and become a problem-solving ninja!\nWhether you're a coding whiz, a UX/UI mastermind, or just someone with a passion for innovation, this Hackathon is your chance to shine!",
            rules: [
                "Each team will consist of two participants.",
                "The teams will receive the theme for the hackathon by registered mail.",
                "Every team is required to submit their ideas before the hackathon starts.",
                "The submission must include a short description of the idea, the cost, and any resources or tools required to develop it.",
                "Each team is given 5 minutes to present their idea to the judges and the audience.",
                "The presentation should include a clear description of the problem being solved, how the idea solves the problem, and any unique features or benefits of the idea.",
            ],
            reg_fees: "100",
            posterImg: "",
            coordinator: ["Arya","Vaishnavi", "Anand", "Devaprasad"],
            contact_coordinator: ["8547589132","9778248972","7306264750", "8086567429"],
        },
        {
            id: 6,
            title: "SPIDERZ-WEB DEVELOPER COMPETITION",
            first_price: "3000",
            second_price: "1000",
            third_price: NULL,
            type: "Individual",
            mode: "Online & Offline",
            date: "19 & 20",
            time: "9:00 AM Onwards",
            desc: "Online (First Round)- 18th Apr 7.00PM to 19th Apr 7.00PM\nOffline (Second Round) - 20th Apr 1.00PM to 20th Apr 4.00PM",
            rules: [
                "Competition will have 2 levels.",
                "In the primary round, a topic will be given to the participants on 18thApril 7.00PM, they can research about the topics in internet.",
                "The participant can take resources from the internet and design an attractive webpage.",
                "There is 24hrs time and they should submit webpage on 19th April 7.00PM.",
                "Late submission is not allowed.",
                "15% participants who are shortlisted from the first level can participate in the second level (20th April 12.00PM - 03.00PM 3Hrs).",
                "Topic will be given on the starting time only. In this level participants can use the resources from internet like videos and photos they can't take any code from the internet, the usage of AI application Strictly prohibited.",
                "Use of mobile phones are not allowed.",
            ],
            reg_fees: "20",
            posterImg: "",
            coordinator: ["Adithyan S Pillai","Neeraj J", "Sreelekshmi"],
            contact_coordinator: ["9605987219","8281307620","8129374881"],
        },
        {
            id: 7,
            title: "TECH WIZARD",
            first_price: "3000",
            second_price: NULL,
            third_price: NULL,
            type: "Individual",
            mode: "Online & Offline",
            date: "20",
            time: "10:00AM Onwards",
            desc: "All the you computer nerds out there, take note. Are you prepared to show your worth? Prepare to participate in the pinnacle of technical competitions. Avail this golden opportunity and be the TECH WIZZZAARD",
            rules: [
                "Participation is open to all. ",
                "Spot registrations are available but limited. ",
                "Decision of the coordinators are final. ",
                "Malpractices are not allowed.",
                "Participants are requested to arrive on time. ",
                "The competition consists of 3 rounds-",
                "Debugging, Blind Coding & PC assembly"
            ],
            reg_fees: "100",
            posterImg: "",
            coordinator: ["Adithya Vijayan","Athira Ajikumar B", "Amith Vinod", "Anandu R", "Kailas Krishna"],
            contact_coordinator: ["7736897590","7736897590","6282535641", "6282535641", "8075653841"],
        },
        {
            id: 8,
            title: "WEBZEIGN-UI DESIGNING",
            first_price: "3000",
            second_price: "1000",
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "11:00 AM – 12:45 PM",
            desc: "WEBZEIGN challenges designers to create visually appealing and user-friendly interfaces for a given topic. Participants are judged on their creativity, functionality, and overall user experience.",
            rules: [
                "WEBZEIGN will be a designing of a mobile application UI , The topic will be given at the time of competition ",
                "Designing tool will be Figma. Workspace will be allotted for each participant by their name",
                "A person has 2 hrs to complete the design, minimum 4 frame required",
            ],
            reg_fees: "20",
            posterImg: "",
            coordinator: ["Harikrishnan","Mathew George", "Sreejith"],
            contact_coordinator: ["9995280526","9947830781","8137006907"],
        },
        {
            id: 9,
            title: "CODE MAFIA – RELAY CODING",
            first_price: "3000",
            second_price: "1000",
            third_price: "",
            type: "Team(3 Members)",
            mode: "Offline",
            date: "20",
            time: "11:00 AM – 12:45 PM",
            desc: "Programmers showcase your programming skills in C and compete to solve a set of challenges in a limited amount of time and wiz exciting prize.",
            rules: [
                "The team should decide the order of players for competing in the particular round.",
                "Each player will have three minutes of time to solve the problem.",
                "After three minutes, the next player can start solving the remaining problem.",
                "The no of rounds will be decided based on the no of participants",
            ],
            reg_fees: "0",
            posterImg: "",
            coordinator: ["A.L Hari Shekhar","Antony K Mathew", "Aravind Suresh0", "M. Raoof"],
            contact_coordinator: ["9847870656","7356304231","7902330867", "9995459326"],
        },
        {
            id: 10,
            title: "PATTERN PRINTING",
            first_price: "3000",
            second_price: "1000",
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "2:00 PM – 4:00 PM",
            desc: "Think you're a pattern printing pro in C? Compete with other coding enthusiasts to see who can generate the most accurate pattern that we provide! Put your skills to the test and showcase your creativity while having fun.",
            rules: [
                "To confirm their eligibility, participants must present a current college ID card to the event.",
                "Each contender is only permitted one entry.",
                "Participants must make sure their answers are comprehensive and submitted correctly before the given time runs out in order to be evaluated.",
                "The location must be reached by the participants on time.",
                "Only the PCs provided by the organizers should be used by participants.",
                "Participants are urged to concentrate on coming up with ideas as quickly and precisely as possible because speed will play a role in determining the winner.",
                "The winners will be the only ones to receive the rewards, which cannot be transferred to anyone else.",
                "Any rule infractions or any misbehaviour will result in exclusion from the competition, and the judges' judgement is final.",
            ],
            reg_fees: "20",
            posterImg: "",
            coordinator: ["Ebin Varghese","Abishek"],
            contact_coordinator: ["7558844341","7907247909"],
        },
        {
            id: 11,
            title: "HYPER LINK ",
            first_price: "1500",
            second_price: "500",
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "20",
            time: "10:00 AM – 12:30 PM",
            desc: "All of us have been there looking at links for clues as to what the page is about and where to go next for our needs.\nIn this competition, we will give you a source word and all that you need to do is click, click and click on the incoming links to reach the word at the destination.",
            rules: [
                "There will be 3 levels for the competition ",
                "Two participants cannot share the same system.",
                "The fastest participant to reach the keyword wins.",
                "Malpractices will result in Disqualification.",
                "The decisions of Judges will be final regarding all the matters of the event.",
                "Use of 'CTRL+F' and other shortcut keys are strictly prohibited",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Ansu Varghese","Aswin S Seshadri", "Abhiram Venugopal"],
            contact_coordinator: ["9605443353","6238088681","8304020968"],
        },
        {
            id: 12,
            title: "PLAY PLEX – GAMING ROOM",
            first_price: NULL,
            second_price: NULL,
            third_price: NULL,
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "Play For Fun, Not for Prize\nExperience the Reality in Ultimate gaming\nThe anticipation comes to an end!!!!\nAre you a hardcore gamer looking for a fun and engaging way to connect with other like-minded gamers? Look no further than our upcoming gaming room event! Join with us for non-stop gaming action, socializing, and friendly competition...10+ Games with highly modified gaming equipment's have worth up to 1 million.\nEntry fees\n20/- (for 15 minutes/per game)\n50/- (for 30 minutes/Any games)\nSo mark your calendar, invite your friends, and get ready to level up at our gaming room event.",
            rules: [
                "Equipment care: Treat gaming equipment with care and report any malfunctions or damage to the volunteers. Do not tamper with or modify the equipment in any way, if any malfunctioning in device happens, it will result you to pay fine of the device amount!!!",
                "Time limits: Time limits may be imposed to ensure that all players have a chance to use the gaming room. Players should be considerate of others and avoid monopolizing the equipment or facilities.",
                "Volunteers instructions: Players should follow any instructions or requests from the volunteers of the gaming room. Failing to comply with rules or volunteers’ instructions may result in suspension or revocation of gaming room privileges.",
            ],
            reg_fees: "20",
            posterImg: "",
            coordinator: ["Justin James","Rahul Mane", "Karthik"],
            contact_coordinator: ["8075512624","9061630557","9567443356"],
        },


    ],
    
    civil: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
        
    ],

    mech: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ],

    electrical: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ],

    basic_science: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ]

}