const events = {
    cse: [
        {
            id: 1,
            title: "Velocity - Type Racer",
            first_price: "1500",
            second_price: "500",
            third_price: NULL,
            type: "Individual",
            mode: "Offline",
            date: "19",
            time: "10:00 AM - 12:00 PM",
            desc: "Think you're the fastest typist around? Prove it! Join our speed typing event, race against the clock, and claim the title of typing master. Exciting prizes await the winner!",
            rules: [
                "He or she must type the entire passage within the allotted time.",
                "Errors will result in loss of points.",
                "Players with the highest Words Per Minute (WPM) wins the game.",
                "Decision of judge's will be final."
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Manu V V","Harigovind S", "Josekutty George"],
            contact_coordinator: ["8921767709","9188358027","8086671175"],
        },
        {
            id: 2,
            title: "SPEED FREAK - NFS GAMING",
            first_price: "1500",
            second_price: "1000",
            third_price: "500",
            type: "Individual",
            mode: "Offline",
            date: "20",
            time: "9:00 AM - 2:30 PM",
            desc: "Get ready to rev your engines and put your racing skills to the test! Compete in the ultimate LAN multiplayer event of Need for Speed and battle it out against other players for the prestigious Racing King title. Do you have what it takes to be crowned the champion?",
            rules: [
                "Players need ‘Not’ bring their laptop to participate in the event.",
                "Event is conducted as two rounds: Preliminary round and Race round.",
                "The Preliminary Round is a walk-in round. The time of completing the circuit will be recorded. This time is used to shortlist the participants to the next round. Note that this will be an individual event.",
                "In the Race Round, the top 16 shortlisted racers compete with each other to win the Race King title.",
                "The 16 players are split into groups of 4 racers each. Two racers are shortlisted from each group after the race. They are then forwarded to the next round.",
                "There are 3 rounds in total for the Race Round.",
                "Players of each round will be asked if they prefer to have car collision on or off.",
            ],
            reg_fees: "30",
            posterImg: "",
            coordinator: ["Arnold Denzil","Abhiram A", "Shajith Joseph"],
            contact_coordinator: ["8078339113","8089618237","9539147591"],
        },
        {
            id: 3,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },


    ],
    
    civil: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
        
    ],

    mech: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ],

    electrical: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ],

    basic_science: [
        {
            id: 1,
            title: "",
            first_price: "",
            second_price: "",
            third_price: "",
            type: "",
            mode: "",
            date: "",
            time: "",
            desc: "",
            rules: [
                "",
                "",
                "",
                "",
            ],
            reg_fees: "",
            posterImg: "",
            coordinator: ["","", ""],
            contact_coordinator: ["","",""],
        },
    ]

}